trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  terraformVersion: '1.3.0'
  azureServiceConnection: 'Your-Service-Connection-Name'  # Update this
  backendResourceGroup: 'tf-backend-rg'                   # Optional, if you set up remote backend
  backendStorageAccount: 'tfbackendstorage'               # Optional
  backendContainerName: 'tfstate'                         # Optional
  backendKey: 'terraform.tfstate'                         # Optional

steps:

- task: UseTerraform@0
  inputs:
    terraformVersion: '$(terraformVersion)'

- task: TerraformInstaller@0
  inputs:
    terraformVersion: '$(terraformVersion)'

- checkout: self

- task: AzureCLI@2
  inputs:
    azureSubscription: '$(azureServiceConnection)'  # Use your Azure DevOps service connection name
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      terraform init
      terraform plan
      terraform apply -auto-approve
    displayName: 'Terraform: Init, Plan, Apply'
