trigger:
  - main

pool:
  vmImage: "ubuntu-latest"

variables:
  - group: MyKeyVaultSecrets # Optional if using variable group

steps:
  - task: AzureKeyVault@2
    inputs:
      azureSubscription: "<My-Service-Connection-Name>" # Replace with your service connection name in Azure DevOps. Ensure there is a service connection set up to access Azure Key Vault.
      KeyVaultName: "<my-keyvault-name>" # Replace with your Key Vault name. If service conneciton is set up, this will be able to access your vault.
      SecretsFilter: "*"
      RunAsPreJob: true

  - script: echo "The secret is $(mySecretName)"
    name: showSecret
    displayName: "Show secret from Key Vault"
