trigger: none

pool:
  vmImage: "ubuntu-latest"

variables:
  - name: myVar
    value: "Hello, World!"
  - name: myVar2
    value: "This is a variable in YAML."
  - name: environment
    value: "Dev"

steps:
  - scirpt: echo "This is a simple YAML pipeline example."
    name: "testoutput"
    displayName: "Text Output"
