 # Trigger the pipeline when changes are pushed to the 'main' branch. Or use the correct branch for the project.
trigger:
- main

# Specify the type of agent (virtual machine) to run the pipeline on.
pool:
  vmImage: 'ubuntu-latest'  # Use the latest version of Ubuntu as the agent OS.

# Define the sequence of steps to build and deploy the application.
steps:
# Step 1: Fetch the source code.
- task: UseGit@1  # This task pulls the code from the repository.
  displayName: 'Fetch Source Code'  # A friendly name shown in the pipeline logs.

# Step 2: Build the application package.
- script: zip -r app.zip .  # The script compresses all files in the directory into a ZIP file.
  displayName: 'Build Web App Package'  # Helps you understand this step in pipeline logs.

# Step 3: Deploy the package to Azure App Service.
- task: AzureRmWebAppDeployment@4  # This task handles deployment to Azure App Service.
  inputs:  # Configuration inputs for the deployment task.
    appType: 'webApp'  # Specify that the deployment is for a web application.
    package: '$(System.DefaultWorkingDirectory)/app.zip'  # Use the package created in Step 2.
    azureSubscription: 'MyAzureSubscription'  # The Azure subscription to use (set up in Azure DevOps service connections).
    WebAppName: 'MyWebApp'  # The name of the App Service in Azure Portal.
  displayName: 'Deploy to Azure App Service'  # Logs show this title during execution.
