apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask-container
          image: flask-k8s:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
# This yaml file defines a Deployment for the Flask application.
# It specifies that there should be 2 replicas of the Flask app,
# each running in a container named "flask-container" using the image "flask-k8s:latest".
# The container listens on port 5000.
# The Deployment ensures that the specified number of replicas is maintained
