apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
# This yaml file defines a Service for the Flask application.
# It selects pods with the label "app: flask-app" and exposes port 80,
# forwarding traffic to port 5000 on the selected pods.
# The type LoadBalancer indicates that this service should be exposed externally.
